# BASIC SETTINGS
title: Dr. Gerald F M Page
email: gerald.page@oregonstate.edu
github: pageg
twitter: gfmpage1
linkedin: gerald-page-88b73187

header_pages:
  - index.md
  - CV.md
  - Publications.md
  - Contact.md

# BUILD SETTINGS
markdown: kramdown
theme: minima
