# BASIC SETTINGS
title: Dr. Gerald F M Page
email: gerald.page@oregonstate.edu
github_username: pageg
linkedin_username: [Gerald_Page](gerald-page-88b73187)

header_pages:
  - index.md
  - CV.md
  - Publications.md
  - Contact.md

# BUILD SETTINGS
markdown: kramdown
theme: minima
