# BASIC SETTINGS
title: Dr. Gerald F M Page
email: gerald.page@csiro.au
github_username: pageg
twitter_username: gfmpage1
linkedin_username: gerald-page-88b73187

header_pages:
  - index.md
  - CV.md
  - Publications.md
  - Software.md
  - Contact.md
  
# BUILD SETTINGS
markdown: kramdown
theme: minima
